apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-trading-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Schwander1/ai-auto-trade-alpha
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-trading
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 10
