apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redis-cluster","namespace":"argo-trading"},"spec":{"ports":[{"port":6379,"targetPort":6379}],"selector":{"app":"redis-cluster"},"type":"ClusterIP"}}
  creationTimestamp: "2025-10-30T06:33:53Z"
  name: redis-cluster
  namespace: argo-trading
  resourceVersion: "3927"
  uid: a01d7afb-451b-423d-ae3a-4e4d5cc2d57a
spec:
  clusterIP: 10.43.100.218
  clusterIPs:
  - 10.43.100.218
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-cluster
  sessionAffinity: None
  type: ClusterIP
