#!/usr/bin/env python3
"""
Show Detailed Signal Information
Displays comprehensive signal details including all metadata
"""
import sys
import sqlite3
from pathlib import Path
from datetime import datetime, timedelta

def find_database():
    """Find signal database"""
    db_paths = [
        Path("/root/argo-production") / "data" / "signals_unified.db",
        Path(__file__).parent.parent / "data" / "signals_unified.db",
        Path(__file__).parent.parent / "argo" / "data" / "signals_unified.db",
    ]

    for db_path in db_paths:
        if db_path.exists():
            return db_path
    return None

def show_detailed_signals(limit=20):
    """Show detailed signal information"""
    db_path = find_database()
    if not db_path:
        print("❌ Signal database not found")
        return

    try:
        conn = sqlite3.connect(str(db_path), timeout=10.0)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        # Get recent signals with all details
        cursor.execute("""
            SELECT
                signal_id,
                symbol,
                action,
                entry_price,
                target_price,
                stop_price,
                confidence,
                timestamp,
                order_id,
                executor_id,
                outcome,
                regime,
                service_type,
                generated_by
            FROM signals
            ORDER BY timestamp DESC
            LIMIT ?
        """, (limit,))

        signals = cursor.fetchall()
        conn.close()

        if not signals:
            print("⚠️  No signals found in database")
            return

        print("=" * 100)
        print("📊 DETAILED SIGNAL INFORMATION")
        print("=" * 100)
        print(f"Total Signals: {len(signals)}")
        print("=" * 100)
        print("")

        columns = [desc[0] for desc in cursor.description]

        for i, sig in enumerate(signals, 1):
            sig_dict = {col: sig[col] for col in columns}

            print(f"Signal #{i}")
            print("-" * 100)
            print(f"  Signal ID:     {sig_dict['signal_id']}")
            print(f"  Symbol:        {sig_dict['symbol']}")
            print(f"  Action:        {sig_dict['action']}")
            print(f"  Entry Price:   ${sig_dict['entry_price']:.2f}")
            if sig_dict.get('target_price'):
                print(f"  Target Price:  ${sig_dict['target_price']:.2f}")
            if sig_dict.get('stop_price'):
                print(f"  Stop Price:    ${sig_dict['stop_price']:.2f}")
            print(f"  Confidence:    {sig_dict['confidence']:.1f}%")
            print(f"  Regime:        {sig_dict.get('regime', 'UNKNOWN')}")
            print(f"  Timestamp:     {sig_dict['timestamp']}")
            print(f"  Service Type:  {sig_dict.get('service_type', 'N/A')}")
            print(f"  Generated By:  {sig_dict.get('generated_by', 'N/A')}")

            if sig_dict.get('order_id'):
                print(f"  ✅ EXECUTED")
                print(f"     Order ID:    {sig_dict['order_id']}")
                print(f"     Executor:    {sig_dict.get('executor_id', 'N/A')}")
                if sig_dict.get('outcome'):
                    print(f"     Outcome:     {sig_dict['outcome']}")
            else:
                print(f"  ⏭️  NOT EXECUTED")

            print("")

        # Summary statistics
        executed = 0
        for s in signals:
            sig_dict = {col: s[col] for col in columns}
            if sig_dict.get('order_id'):
                executed += 1
        not_executed = len(signals) - executed

        print("=" * 100)
        print("📈 SUMMARY")
        print("=" * 100)
        print(f"Total Signals:     {len(signals)}")
        print(f"Executed:          {executed} ({executed/len(signals)*100:.1f}%)")
        print(f"Not Executed:      {not_executed} ({not_executed/len(signals)*100:.1f}%)")

        # By symbol
        symbols = {}
        for sig in signals:
            sig_dict = {col: sig[col] for col in columns}
            sym = sig_dict['symbol']
            if sym not in symbols:
                symbols[sym] = {'total': 0, 'executed': 0}
            symbols[sym]['total'] += 1
            if sig_dict.get('order_id'):
                symbols[sym]['executed'] += 1

        print(f"\nBy Symbol:")
        for sym, stats in sorted(symbols.items()):
            exec_rate = (stats['executed'] / stats['total'] * 100) if stats['total'] > 0 else 0
            print(f"  {sym}: {stats['total']} signals, {stats['executed']} executed ({exec_rate:.1f}%)")

        # By action
        actions = {}
        for sig in signals:
            sig_dict = {col: sig[col] for col in columns}
            act = sig_dict['action']
            if act not in actions:
                actions[act] = {'total': 0, 'executed': 0}
            actions[act]['total'] += 1
            if sig_dict.get('order_id'):
                actions[act]['executed'] += 1

        print(f"\nBy Action:")
        for act, stats in sorted(actions.items()):
            exec_rate = (stats['executed'] / stats['total'] * 100) if stats['total'] > 0 else 0
            print(f"  {act}: {stats['total']} signals, {stats['executed']} executed ({exec_rate:.1f}%)")

        print("=" * 100)

    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    limit = int(sys.argv[1]) if len(sys.argv) > 1 else 20
    show_detailed_signals(limit)
